"""NetworkManager dispatcher hook (02-hardware §7.4): boot / hot-plug automation.

Renders the bash script installed at ``DISPATCHER_PATH``. NetworkManager-dispatcher(8)
runs it **as root** for every device event; on ``up``/``down`` of a physical
ethernet device it detaches a worker that (after a short settle) runs
``netsetup match --repair`` under a ``flock``. Root needs no polkit grant, so this
converges the arm NICs even when nobody is logged in.

Everything machine-specific (venv python, arm list, state path) is baked in at
install time; the operator-facing knobs (lock/log paths, settle delay, sysfs
root) can be overridden through ``MAVIS_NETSETUP_*`` environment variables — the
tests drive the script that way against a fake sysfs and a stub python.
"""

from __future__ import annotations

import datetime as _dt
import shlex
import sys
from pathlib import Path

from .state import SYSTEM_STATE_PATH
from .types import ArmNet

DISPATCHER_PATH = Path("/etc/NetworkManager/dispatcher.d/90-mavis-netsetup")
LOCK_PATH = Path("/run/lock/mavis-netsetup.lock")
LOG_PATH = Path("/var/log/mavis-netsetup.log")
SETTLE_S = 2  # let NM finish the burst of events one cable produces
LOCK_WAIT_S = 600  # a queued event waits this long for a running repair, then gives up
MODULE = "apollo_mavis_v2_hardware.netsetup"

_TEMPLATE = r"""#!/bin/bash
# 90-mavis-netsetup -- NetworkManager dispatcher hook for apollo-mavis-v2 netsetup.
# GENERATED by `python -m apollo_mavis_v2_hardware.netsetup install` (@GENERATED_AT@);
# re-run install to regenerate. Design: docs/design/02-hardware.md section 7.4.
#
# NetworkManager-dispatcher(8) runs this as root for every device event
# ($1 = interface, $2 = action). On `up`/`down` of a PHYSICAL ETHERNET device it
# schedules `netsetup match --repair`, which verifies first and re-probes only what
# is broken, so the arm NICs converge onto their profiles at boot and after cable
# (re)plugs/swaps -- for any (or no) logged-in account. Root needs no polkit grant.
#
# The heavy work runs detached (NM kills slow dispatcher scripts) under a flock so
# concurrent events serialize. A converged system produces no NM changes and hence
# no further events: no feedback loop.
set -u
export PATH=/usr/sbin:/usr/bin:/sbin:/bin
export LC_ALL=C

PYTHON=@PYTHON@
STATE=@STATE@
ARM_ARGS=(@ARM_ARGS@)
LOCK="${MAVIS_NETSETUP_LOCK:-@LOCK@}"
LOG="${MAVIS_NETSETUP_LOG:-@LOG@}"
SETTLE_S="${MAVIS_NETSETUP_SETTLE_S:-@SETTLE_S@}"
LOCK_WAIT_S=@LOCK_WAIT_S@
SYSFS_NET="${MAVIS_NETSETUP_SYSFS_NET:-/sys/class/net}"

IFACE="${1:-}"
ACTION="${2:-}"

log() {
    if ! printf '%s [%s] %s\n' "$(date -Is)" "$$" "$*" >>"$LOG" 2>/dev/null; then
        logger -t mavis-netsetup -- "$*" 2>/dev/null || true
    fi
}

# --- worker (re-exec'd detached): settle, serialize, repair -------------------
if [ "${MAVIS_NETSETUP_WORKER:-}" = "1" ]; then
    sleep "$SETTLE_S"
    log "repair start ($IFACE $ACTION)"
    flock -w "$LOCK_WAIT_S" "$LOCK" \
        "$PYTHON" -m @MODULE@ match --repair --state "$STATE" "${ARM_ARGS[@]}"
    rc=$?
    log "repair done rc=$rc ($IFACE $ACTION)"
    exit 0
fi

# --- dispatcher entry: filter, then detach ------------------------------------
case "$ACTION" in
    up|down) ;;
    *) exit 0 ;;  # pre-up/pre-down/dhcp*/hostname/connectivity-change/vpn-*
esac
[ -n "$IFACE" ] || exit 0

# Physical ethernet only: ARPHRD_ETHER (type 1), backed by a bus device
# (/device symlink = PCI/USB; bridges, veth, tap, tun, lo have none), not wireless.
[ "$(cat "$SYSFS_NET/$IFACE/type" 2>/dev/null)" = "1" ] || exit 0
[ -e "$SYSFS_NET/$IFACE/device" ] || exit 0
if [ -e "$SYSFS_NET/$IFACE/wireless" ] || [ -e "$SYSFS_NET/$IFACE/phy80211" ]; then
    exit 0
fi
[ -e "$SYSFS_NET/$IFACE/bridge" ] && exit 0

if [ ! -x "$PYTHON" ]; then
    log "skip $IFACE $ACTION: python missing at $PYTHON (re-run: netsetup install)"
    exit 0
fi

log "event $IFACE $ACTION uuid=${CONNECTION_UUID:-} id=${CONNECTION_ID:-}" \
    "-> match --repair in ${SETTLE_S}s"
MAVIS_NETSETUP_WORKER=1 setsid -f "$0" "$IFACE" "$ACTION" </dev/null >>"$LOG" 2>&1
exit 0
"""


def arm_spec(arm: ArmNet) -> str:
    """Inverse of ``__main__._parse_arm``: ``name=ip[/prefix][,host=IP]``."""
    spec = f"{arm.name}={arm.ip}"
    if arm.prefix != 24:
        spec += f"/{arm.prefix}"
    if arm.host_ip:
        spec += f",host={arm.host_ip}"
    return spec


def arm_args(arms: list[ArmNet]) -> list[str]:
    out: list[str] = []
    for arm in arms:
        out += ["--arm", arm_spec(arm)]
    return out


def default_python() -> Path:
    """The interpreter running netsetup — inside ``uv run`` that is the venv's
    ``.venv/bin/python`` (a symlink; do NOT resolve it, the venv is found via
    the symlink's own directory)."""
    return Path(sys.executable)


def repair_argv(python: Path, arms: list[ArmNet], state: Path = SYSTEM_STATE_PATH) -> list[str]:
    """Exactly what the worker executes (documented / asserted by tests)."""
    return [str(python), "-m", MODULE, "match", "--repair", "--state", str(state),
            *arm_args(arms)]


def match_argv(python: Path, arms: list[ArmNet], state: Path = SYSTEM_STATE_PATH) -> list[str]:
    """The one-shot initial match ``install`` runs through sudo."""
    return [str(python), "-m", MODULE, "match", "--state", str(state), *arm_args(arms)]


def render_dispatcher(
    python: Path,
    arms: list[ArmNet],
    state: Path = SYSTEM_STATE_PATH,
    generated_at: str | None = None,
    lock: Path = LOCK_PATH,
    log: Path = LOG_PATH,
    settle_s: int = SETTLE_S,
    lock_wait_s: int = LOCK_WAIT_S,
) -> str:
    """Render the dispatcher script (bash). ``generated_at`` defaults to today."""
    if not arms:
        raise ValueError("render_dispatcher needs at least one arm (--arm/--config)")
    stamp = generated_at or _dt.date.today().isoformat()
    return (
        _TEMPLATE.replace("@GENERATED_AT@", stamp)
        .replace("@PYTHON@", shlex.quote(str(python)))
        .replace("@STATE@", shlex.quote(str(state)))
        .replace("@ARM_ARGS@", shlex.join(arm_args(arms)))
        .replace("@LOCK@", str(lock))
        .replace("@LOG@", str(log))
        .replace("@SETTLE_S@", str(int(settle_s)))
        .replace("@LOCK_WAIT_S@", str(int(lock_wait_s)))
        .replace("@MODULE@", MODULE)
    )
